# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "realwin-serverless"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
stack_name = "realwin-serverless-prod"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "realwin-serverless-prod"
region = "us-east-1"
disable_rollback = true
image_repositories = []

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
stack_name = "realwin-serverless-dev"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "realwin-serverless-dev"
region = "us-east-1"
disable_rollback = true
image_repository = "008971631957.dkr.ecr.us-east-1.amazonaws.com/video-analysis"


[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
stack_name = "realwin-serverless-default"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "realwin-serverless-default"
region = "us-east-1"
disable_rollback = true
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"


